# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:               Justice Amoh
tagline:             'PhD student at Thayer School Of Engineering'
description:         'A researcher at the <a href="http://engineering.dartmouth.edu/analoglab/" target="_blank">Analog Lab</a> at Thayer. Research areas include Machine Learning, Acoustics, Biomedical Devices and Embedded Systems.'
url:                 http://justiceamoh.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Justice Amoh
  url:               https://twitter.com/mdo
  email:             justiceamoh@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate_path: "page:num"