name: Blistering Barnacles
description: Research Blogging.
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://justiceamoh.me'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'
email: justice.amoh.jr.th@dartmouth.edu


# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Justice Amoh'
authorTwitter:  'justiceamoh'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
